name = "Readline"
version = "1.0.0"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
name = "Readline"
lazy = "false"
src_version = "8.2.0"
platform = "aarch64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:cfbaab90812c6f04cae80371c65454eb42c8862a"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:624dea44ff32a54287a5b69dd368963e0d1a0b784857fa3124a1918e8fd9daf1"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.0-bb2_tests/Readline-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:cb37b41d97017a25b7d02c21393f7aaa88be3894"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:1718740b509c7a5eef09b6283a58feaae9520e633c618587578ec22719268a2b"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.0-bb2_tests/Readline-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libhistory"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libhistory.so.8"
    type = "library"
    path = "lib/libhistory.so.8.2"
    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libreadline"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libreadline.so.8"
    type = "library"
    path = "lib/libreadline.so.8.2"

    [[builds.sources]]
    treehash = "sha1:b001ca786ca25dd07eeead4688b98fa487e57303"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz"
    [[builds.sources]]
    treehash = "sha1:a13ff4285079cdb957e1619668b5e254615b0de6"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-001"

    [builds.artifact]
    treehash = "sha1:86dbbae0fc03bf1d84afa1251408a42a6015e612"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:a403c34db2b09e57dc041ea53c631a2d8e1dd0a416d3e70fe001b879b92be5ca"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.0-bb2_tests/Readline-v1.0.0-aarch64-linux-gnu.tar.gz"
