name = "Readline"
version = "1.0.0"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "default"
lazy = "false"
src_version = "8.1.0"
platform = "aarch64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:585faa32cb65b7e942ccb9d108ddfb544959f954"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:4f0fa5ab29396ed018c570f1a16090fe887b081d6b417797310a099938963e0c"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.0/Readline-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:4f24a8bb4c751c872132755e2cdcab77bc307fd1"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:abd2336a3f64e43b6e7b52121e1ac9c71f962a57e41781949a1f51ef30eb2fd4"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.0/Readline-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libhistory"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libhistory.so.8"
    type = "library"
    path = "lib/libhistory.so.8.1"
    [[builds.products]]
    deps = []
    name = "libreadline"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libreadline.so.8"
    type = "library"
    path = "lib/libreadline.so.8.1"

    [[builds.sources]]
    treehash = "sha1:55705b69b0b41f01be5351c4fb557b7615e64072"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.1.tar.gz"
    [[builds.sources]]
    treehash = "sha1:2f99282c87f3ae0e976da076a98e5f8588220e25"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.1-patches/readline81-001"

    [builds.artifact]
    treehash = "sha1:b18bc5bdcff9c62785e46d19dcdce3717ce10335"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:dd29c0b31ad6f096dd61cd1ac768ebe4d926460fb382cc8b2e30cc2dd92094cb"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.0/Readline-v1.0.0-aarch64-linux-gnu.tar.gz"
