name = "Readline"
version = "1.0.11"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
name = "Readline"
lazy = "false"
src_version = "8.2.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:595f8a8cfe6dbade4f1e81e5367393863f1413d2"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:0ebc239fbcafbaae2348b8d7ab54f518a9dbc353fba82708ab5191a2c8773f80"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.11-GCCBoostrap/Readline-build_log-v1.0.11-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:7a979ed4a1a80d41a71df4e3bd3eeb900288ce9e"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:aaf227f2768059482475283fc06a353c257e6c31ee965729a5818b62c123f68b"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.11-GCCBoostrap/Readline-extract_log-v1.0.11-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libreadline"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libreadline.so.8"
    type = "library"
    path = "lib/libreadline.so.8.2"
    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libhistory"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libhistory.so.8"
    type = "library"
    path = "lib/libhistory.so.8.2"

    [[builds.sources]]
    treehash = "sha1:b001ca786ca25dd07eeead4688b98fa487e57303"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz"
    [[builds.sources]]
    treehash = "sha1:a13ff4285079cdb957e1619668b5e254615b0de6"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-001"

    [builds.artifact]
    treehash = "sha1:e1400c38815c5d9ef1e68058f3f2178cb1437342"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:d05d480a8fc420320a9e67efc22f476648a46f96198407f6a29f3276fba989bd"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.11-GCCBoostrap/Readline-v1.0.11-x86_64-linux-gnu.tar.gz"
