name = "Readline"
version = "1.0.1"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
name = "Readline"
lazy = "false"
src_version = "8.2.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:375f3d33c74a48195bbdad506332fb9fb731c26c"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:d7a926ec242863fb5881cca2e3ba5cafe464dbe13f400514704daa1f847d616c"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.1-GCCBoostrap-x86_64-linux-gnu/Readline-build_log-v1.0.1-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:4c6a9205fee2188aae793790c3f1d45c392521c7"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:b92126cc55316d35c8f73cc48b115da4155edd63e5ea938154db6b5c65ec9b7b"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.1-GCCBoostrap-x86_64-linux-gnu/Readline-extract_log-v1.0.1-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libreadline"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libreadline.so.8"
    type = "library"
    path = "lib/libreadline.so.8.2"
    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libhistory"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libhistory.so.8"
    type = "library"
    path = "lib/libhistory.so.8.2"

    [[builds.sources]]
    treehash = "sha1:b001ca786ca25dd07eeead4688b98fa487e57303"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz"
    [[builds.sources]]
    treehash = "sha1:a13ff4285079cdb957e1619668b5e254615b0de6"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-001"

    [builds.artifact]
    treehash = "sha1:e1400c38815c5d9ef1e68058f3f2178cb1437342"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:e72d48131568ce11c5407fd47cd84c3e8cc6436be62a6f4031b6954f6877d0b2"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.1-GCCBoostrap-x86_64-linux-gnu/Readline-v1.0.1-x86_64-linux-gnu.tar.gz"
