name = "Readline"
version = "1.0.0"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "default"
lazy = "false"
src_version = "8.1.0"
platform = "aarch64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:1d087407a13f3ca0413cd0f91260953c279d27fb"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:ba5f17bdac061e130c89569a4bca4937e0a437eb2c5682b2e8fda667330f4614"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.0/Readline-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:4f24a8bb4c751c872132755e2cdcab77bc307fd1"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:94c1c50818ed24c3f5464f3ca02ae92eea5b45f864a9f8c6b897ef32065ee0fc"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.0/Readline-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libhistory"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libhistory.so.8"
    type = "library"
    path = "lib/libhistory.so.8.1"
    [[builds.products]]
    deps = []
    name = "libreadline"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libreadline.so.8"
    type = "library"
    path = "lib/libreadline.so.8.1"

    [[builds.sources]]
    treehash = "sha1:55705b69b0b41f01be5351c4fb557b7615e64072"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.1.tar.gz"
    [[builds.sources]]
    treehash = "sha1:2f99282c87f3ae0e976da076a98e5f8588220e25"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.1-patches/readline81-001"

    [builds.artifact]
    treehash = "sha1:6f5380a7baea0fec592d88f687342013fff5b8dd"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:dc97fc073684e9f03b03e511f2ff5b75be17829bda25f9ddd6d5266ea14b62a6"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.0/Readline-v1.0.0-aarch64-linux-gnu.tar.gz"
