name = "Readline"
version = "1.0.10"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
name = "Readline"
lazy = "false"
src_version = "8.2.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:4ccb59edc9a3e0a1e3e7b04483d58a6d6853d965"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:39bbdf0af2b8d9640880643c88a5c5a656bd2e5650854d179e481e2f7f65fdd7"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.10-GCCBoostrap/Readline-build_log-v1.0.10-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:2b23b3428eb07feb7b452caecda753e50f0b5fd4"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:f5be4ad8d13df4a81f3ade8b21ed5fcd84dc52ac2593f6f2ee6bd98bba528c53"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.10-GCCBoostrap/Readline-extract_log-v1.0.10-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libreadline"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libreadline.so.8"
    type = "library"
    path = "lib/libreadline.so.8.2"
    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libhistory"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libhistory.so.8"
    type = "library"
    path = "lib/libhistory.so.8.2"

    [[builds.sources]]
    treehash = "sha1:b001ca786ca25dd07eeead4688b98fa487e57303"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz"
    [[builds.sources]]
    treehash = "sha1:a13ff4285079cdb957e1619668b5e254615b0de6"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-001"

    [builds.artifact]
    treehash = "sha1:e1400c38815c5d9ef1e68058f3f2178cb1437342"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:1ab535611de99a40c1408455e0870b046f50fa2193a713e00e9dc028c56b21c0"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.10-GCCBoostrap/Readline-v1.0.10-x86_64-linux-gnu.tar.gz"
