name = "Readline"
version = "8.2.2"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
name = "Readline"
lazy = "false"
src_version = "8.2.0"
platform = "aarch64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:4cdf01b116fd8aae0c710d374e60c8d5df53675b"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:6701bf96cc0c94f76ae99e46da9b27a4eb8fd0f470ba4e8e3148c8f94614dfba"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.2.2-GCCBoostrap-aarch64-linux-gnu/Readline-build_log-v8.2.2-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:24438843f19e017c9c4de7b048bcdf634a025871"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:25f26c9077ceb51451b7678321abd9718a8ac1700e6c713607a0a3dcab74a7d2"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.2.2-GCCBoostrap-aarch64-linux-gnu/Readline-extract_log-v8.2.2-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libreadline"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libreadline.so.8"
    type = "library"
    path = "lib/libreadline.so.8.2"
    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libhistory"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libhistory.so.8"
    type = "library"
    path = "lib/libhistory.so.8.2"

    [[builds.sources]]
    treehash = "sha1:b001ca786ca25dd07eeead4688b98fa487e57303"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz"
    [[builds.sources]]
    treehash = "sha1:a13ff4285079cdb957e1619668b5e254615b0de6"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-001"

    [builds.artifact]
    treehash = "sha1:86dbbae0fc03bf1d84afa1251408a42a6015e612"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:d5ce196e0b694f685ee4ceca6015374ed7ea3908e5d5d7e117b125c9b02224ac"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.2.2-GCCBoostrap-aarch64-linux-gnu/Readline-v8.2.2-aarch64-linux-gnu.tar.gz"
