name = "Readline"
version = "1.0.16"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
name = "Readline"
lazy = "false"
src_version = "8.2.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:c76b751aea7986b34568f8a5085043020f14d4ea"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:b9663c6d5a979480fa1ab358fb7d44f680b91b2e77e4a6885c463e038c4d86c6"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.16-GCCBoostrap/Readline-build_log-v1.0.16-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:4d6a552bf5abdac5ca2435b634582beebee03280"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:ac74b94a548688193f06af7c62e85e6ae77f7459ca3d7646d78b5620e41eae0a"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.16-GCCBoostrap/Readline-extract_log-v1.0.16-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libreadline"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libreadline.so.8"
    type = "library"
    path = "lib/libreadline.so.8.2"
    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libhistory"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libhistory.so.8"
    type = "library"
    path = "lib/libhistory.so.8.2"

    [[builds.sources]]
    treehash = "sha1:b001ca786ca25dd07eeead4688b98fa487e57303"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz"
    [[builds.sources]]
    treehash = "sha1:a13ff4285079cdb957e1619668b5e254615b0de6"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-001"

    [builds.artifact]
    treehash = "sha1:e1400c38815c5d9ef1e68058f3f2178cb1437342"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:3530e96501ff788db66b8ec5119d0ae83d803b747c646b1b7c1e46ba7b482815"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.16-GCCBoostrap/Readline-v1.0.16-x86_64-linux-gnu.tar.gz"
