name = "Readline"
version = "1.0.0"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
name = "default"
lazy = "false"
src_version = "8.1.0"
platform = "aarch64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:7ffd7b74edf22145e781eb6fe54662d0769c3a7b"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:5b45c6609036c66c60e062b35c8fd21ae6f4d5ead37adb70b4ea5858219dd376"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.0/Readline-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:7d5cf295dfcc5685108232ea97ea8969516d157e"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:75fc12f115c0a662725e50e950ad35596b54d09c5426eec8719224bb113d986b"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.0/Readline-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libhistory"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libhistory.so.8"
    type = "library"
    path = "lib/libhistory.so.8.1"
    [[builds.products]]
    deps = []
    name = "libreadline"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libreadline.so.8"
    type = "library"
    path = "lib/libreadline.so.8.1"

    [[builds.sources]]
    treehash = "sha1:55705b69b0b41f01be5351c4fb557b7615e64072"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.1.tar.gz"
    [[builds.sources]]
    treehash = "sha1:2f99282c87f3ae0e976da076a98e5f8588220e25"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.1-patches/readline81-001"

    [builds.artifact]
    treehash = "sha1:b18bc5bdcff9c62785e46d19dcdce3717ce10335"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:6c082f3a3579fc90ef0b152c601f99b55f7a88a28bea78043b32d945ca498fdf"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.0/Readline-v1.0.0-aarch64-linux-gnu.tar.gz"
