name = "Readline"
version = "1.0.15"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
name = "Readline"
lazy = "false"
src_version = "8.2.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:6b3cd359256d9717f27c6306f7f3f3fb4426f019"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:318b6deda1fc02f4facd08db2e3de5790b0aae200c06052f297e1c86a3ceec35"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.15-GCCBoostrap/Readline-build_log-v1.0.15-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:c6beecc5e669e49e7df9871940a43b981a92abde"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:e2739f17380cdcef703cd0e9fdab2dcd3acca63b60934af3356a2483091502b2"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.15-GCCBoostrap/Readline-extract_log-v1.0.15-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libreadline"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libreadline.so.8"
    type = "library"
    path = "lib/libreadline.so.8.2"
    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libhistory"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libhistory.so.8"
    type = "library"
    path = "lib/libhistory.so.8.2"

    [[builds.sources]]
    treehash = "sha1:b001ca786ca25dd07eeead4688b98fa487e57303"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz"
    [[builds.sources]]
    treehash = "sha1:a13ff4285079cdb957e1619668b5e254615b0de6"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-001"

    [builds.artifact]
    treehash = "sha1:e1400c38815c5d9ef1e68058f3f2178cb1437342"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:e769f79f759718fba8555f05b51430152aa009dc2d6a5eb27b9035dc2415862a"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.15-GCCBoostrap/Readline-v1.0.15-x86_64-linux-gnu.tar.gz"
