name = "Readline"
version = "1.0.8"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
name = "Readline"
lazy = "false"
src_version = "8.2.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:3c531a58a6d81cf44b0c93f39f1b9154c025f022"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:ffce404e3a21cec8c92bc244836f4c23f5d7c1a8055ee0cd821bd2b0b9944885"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.8-GCCBoostrap/Readline-build_log-v1.0.8-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:ddf2b2c9a22b426a1d90295a29d4917182696fa5"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:cebd43d7eea745a6718d11c0eddc65caf01086972f7f463745fff4511218bfdf"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.8-GCCBoostrap/Readline-extract_log-v1.0.8-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libreadline"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libreadline.so.8"
    type = "library"
    path = "lib/libreadline.so.8.2"
    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libhistory"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libhistory.so.8"
    type = "library"
    path = "lib/libhistory.so.8.2"

    [[builds.sources]]
    treehash = "sha1:b001ca786ca25dd07eeead4688b98fa487e57303"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz"
    [[builds.sources]]
    treehash = "sha1:a13ff4285079cdb957e1619668b5e254615b0de6"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-001"

    [builds.artifact]
    treehash = "sha1:e1400c38815c5d9ef1e68058f3f2178cb1437342"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:fb42e8961e48ea179739dead6a8b29535fc68ef087aae2c0e83bd295cc43b69f"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v1.0.8-GCCBoostrap/Readline-v1.0.8-x86_64-linux-gnu.tar.gz"
