name = "Readline"
version = "8.2.3"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
name = "Readline"
lazy = "false"
src_version = "8.2.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:35338beccf13c542a73ee346345d1634f8637223"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:6dc986335d1422d38e2933c2dac745c3dca0f8a87809ae8e3c8329afc0ec76cf"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.2.3-GCCBootstrap-x86_64-linux-gnu/Readline-build_log-v8.2.3-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:e95cb7f9792f59c31693df73a534633555eee586"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:2300dd551fa3daef6ac96bb92460c6baed4fcdf93dfcbb8d621e5781ffd658e8"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.2.3-GCCBootstrap-x86_64-linux-gnu/Readline-extract_log-v8.2.3-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libreadline"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libreadline.so.8"
    type = "library"
    path = "lib/libreadline.so.8.2"
    [[builds.products]]
    deps = ["Ncurses_jll.libncurses"]
    name = "libhistory"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libhistory.so.8"
    type = "library"
    path = "lib/libhistory.so.8.2"

    [[builds.sources]]
    treehash = "sha1:b001ca786ca25dd07eeead4688b98fa487e57303"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz"
    [[builds.sources]]
    treehash = "sha1:a13ff4285079cdb957e1619668b5e254615b0de6"
    url = "https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-001"

    [builds.artifact]
    treehash = "sha1:e1400c38815c5d9ef1e68058f3f2178cb1437342"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:0152c799ea38aad0b121f97cbe99baa7bdc0c42019fd78ca0b6263112098c578"
        url = "https://github.com/staticfloat/Readline_jll.jl/releases/download/v8.2.3-GCCBootstrap-x86_64-linux-gnu/Readline-v8.2.3-x86_64-linux-gnu.tar.gz"
