# Autogenerated wrapper script for Readline_jll for x86_64-unknown-freebsd
export libhistory, libreadline

using Ncurses_jll
JLLWrappers.@generate_wrapper_header("Readline")
JLLWrappers.@declare_library_product(libhistory, "libhistory.so.8")
JLLWrappers.@declare_library_product(libreadline, "libreadline.so.8")
function __init__()
    JLLWrappers.@generate_init_header(Ncurses_jll)
    JLLWrappers.@init_library_product(
        libhistory,
        "lib/libhistory.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libreadline,
        "lib/libreadline.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
